apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gt-dash
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: sevenleo/github-dashboard
    argocd-image-updater.argoproj.io/sevenleo.github-dashboard.update-strategy: latest
    argocd-image-updater.argoproj.io/sevenleo.github-dashboard.helm.values: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/leonardosete/git-wkf-dash.git
    targetRevision: develop
    path: infra/helm-charts/gt-dash
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gt-dash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Namespace
      name: gt-dash
      jsonPointers:
        - /metadata/labels
